"""empty message

Revision ID: b21547f1aa8d
Revises: 89463cf21b29
Create Date: 2023-05-19 13:55:22.558310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21547f1aa8d'
down_revision = '89463cf21b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('answerId', sa.INTEGER(), nullable=False),
    sa.Column('upvote', sa.BOOLEAN(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['answerId'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###